# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GXxHcYlLdEMJsv6Wex8NEPQUSxXWuY0
"""



import nltk
import re
import string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Download required NLTK data
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('punkt_tab', quiet=True)

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

# -----------------------------
# Expanded Training Data
# -----------------------------
texts = [
    # Positive
    "I am very happy",
    "This is amazing",
    "I love this product",
    "You are doing great",
    "I feel fantastic today",
    "That was wonderful",
    "This makes me smile",
    "I am excited about this",
    "Everything is awesome",
    "I am proud of you",
    #negative
    "I am very sad",
    "This is terrible",
    "I hate this",
    "I feel disappointed",
    "This is the worst",
    "I am upset",
    "That was horrible",
    "I feel angry",
    "This makes me frustrated",
    "I am not happy"
]

labels = [1]*10 + [0]*10

# -----------------------------
# Preprocessing Function
# -----------------------------
def preprocess(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    return " ".join(tokens)

processed_texts = [preprocess(t) for t in texts]

# -----------------------------
# TF-IDF + Model Training
# -----------------------------
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(processed_texts)

model = LogisticRegression()
model.fit(X, labels)

print("🤖 Chatbot Ready! Type 'exit' to stop.\n")

# -----------------------------
# Interactive Chat Loop
# -----------------------------
while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("Chatbot: Goodbye! 👋")
        break

    processed_input = preprocess(user_input)
    input_vector = vectorizer.transform([processed_input])
    prediction = model.predict(input_vector)[0]

    if prediction == 1:
        print("Chatbot: 😊 You sound positive!")
    else:
        print("Chatbot: 😔 You seem upset.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Creating simple dataset
data = {
    "Area": [500, 800, 1200, 1500, 2000, 2500],
    "Price": [150000, 200000, 300000, 350000, 450000, 500000]
}

df = pd.DataFrame(data)

X = df[["Area"]]
y = df["Price"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluation
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# Visualization
plt.scatter(X, y, color="blue")
plt.plot(X, model.predict(X), color="red")
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Linear Regression - House Price Prediction")
plt.show()